# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tamara Freeman - Actor
email: tamarabfreeman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tamara Freeman is a Canadian Voice Actor, perhaps best known for her role as
  Rebecca in Hailey and the Hero Hearts
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tamarafreeman.ca" # the base hostname & protocol for your site
author: Tamara Freeman
exclude:
  - .idea

# Build settings
markdown: kramdown
